### ISSUE TITLE
Question: Is there any combination missing in likelihood of occSSrn0 ?

### ISSUE THREAD

**Issue by MattWu19950517** [mikemeredith/wiqid#6]
Hi, sorry for bothering.

I have a question about parameter estimation in function `occSSrn0`.
The likelihood function stated in Royle & Nichols (2003) has a combination <img src="https://render.githubusercontent.com/render/math?math=\binom{T}{w_{i.}}"> involved, which is: 
<img src="https://render.githubusercontent.com/render/math?math=L(w_{i.})=\sum_{k=0}^{K}\binom{T}{w_{i.}}p^{w_{i.}}_k(1-p_{k})^{T-w_{i.}}f_k">
But the for-loop used to compute log-likelihood in function `nll` didn’t !
```R
      llh <- 0
      for(i in seq_along(n)) {
        tmp <- if(y[i]==0) 0 else log1mrpart*y[i] # because log(0) * 0 -> NaN
        llh <- llh + logSumExp(tmp + logrpart*(n[i]-y[i]) + logNpart)
      }
```
However, ` occSSrn0` has the same results on ` weta` as PRESENCE did.
Please correct me if I misunderstand anything.

Thanks

**Comment by mikemeredith** [comment]
Hi MattWu,

The term <img src="https://render.githubusercontent.com/render/math?math=\binom{T}{w_{i.}}"> is constant for any particular data set and does not depend on the parameter values. As such, including or omitting the term has no effect on the relative values of the likelihood and does not affect the estimates.

It will affect the maximized log likelihood and hence AIC, but will be the same for all models and have no effect on deltaAIC or model weights.

In theory, likelihood is only defined up to a constant of proportionality, so it's okay to just ignore these constant terms. My own feeling is that it is preferable to include them, but here I wanted to reproduce the same AIC values as those returned by PRESENCE package, which apparently ignores the constants.

Mike
